# This file configures the build and deployment settings for Netlify.

# The [build] block specifies the build command and the directory
# where the output of the build will be located.
[build]
  command = "npm run build"
  publish = ".next"

# The [functions] block allows you to configure Netlify Functions.
# We set a global timeout for all functions to prevent them from
# being terminated prematurely, which is common for AI-related tasks.
[functions]
  # Set the timeout to 120 seconds for all serverless functions
  timeout = 120
