[build]
  command = "next build"
  publish = ".next"

[functions]
  # Increase the timeout for all serverless functions
  # to allow for longer-running AI operations.
  # Netlify's default is 10 seconds, which can be too short.
  timeout = 120

[[redirects]]
  from = "/_next/static/*"
  to = "/static/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200
